climate_data_infras:
  target: dev

  outputs:
    dev:
      type: postgres
      host: "{{ env_var('DBT_RDS_HOST') }}"
      port: "{{ env_var('DBT_RDS_PORT') | int }}"
      user: "{{ env_var('DBT_RDS_USER') }}"
      password: "{{ env_var('DBT_RDS_PASSWORD') }}"
      dbname: "{{ env_var('DBT_RDS_DATABASE') }}"
      schema: dbt_dev
      threads: 1
      sslmode: require
